import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import domainsRouter from "./domains";
import controlsRouter from "./controls";
import evidenceRouter from "./evidence";
import tasksRouter from "./tasks";
import poamsRouter from "./poams";
import dashboardRouter from "./dashboard";
import assessorRouter from "./assessor";
import auditRouter from "./auditlogs";
import documentsRouter from "./documents";
import organizationsRouter from "./organizations";
import monitoringRouter from "./monitoring";
import sspRouter from "./ssp";
import reportsRouter from "./reports";
import adminRouter from "./admin";
import configureRouter from "./configure";
import roadmapRouter from "./roadmap";
import readinessRouter from "./readiness";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(organizationsRouter);
router.use(domainsRouter);
router.use(controlsRouter);
router.use(evidenceRouter);
router.use(tasksRouter);
router.use(poamsRouter);
router.use(dashboardRouter);
router.use(assessorRouter);
router.use(auditRouter);
router.use(documentsRouter);
router.use(monitoringRouter);
router.use(sspRouter);
router.use(reportsRouter);
router.use(adminRouter);
router.use(configureRouter);
router.use(roadmapRouter);
router.use(readinessRouter);

export default router;
