import {
  pgTable,
  text,
  timestamp,
  json,
  pgEnum,
} from "drizzle-orm/pg-core";
import { usersTable } from "./users";
import { organizationsTable } from "./organizations";

export const auditActionEnum = pgEnum("audit_action", [
  "created",
  "updated",
  "deleted",
  "approved",
  "rejected",
  "submitted",
  "reviewed",
  "assigned",
  "uploaded",
  "downloaded",
  "exported",
  "status_changed",
  "comment_added",
  "link_added",
  "link_removed",
  "logged_in",
  "logged_out",
  "completed",
  "closed",
  "superseded",
  "marked_stale",
  "reopened",
  "viewed",
  "deactivated",
  "activated",
  "password_reset",
  "org_access_changed",
  "create",
  "update",
  "generate",
  "submit_review",
  "approve",
  "reject",
  "activate",
  "archive",
  "complete",
  "complete_checklist",
  "run_doc_checks",
  "password_changed",
  "login_failed",
  "account_locked",
  "account_unlocked",
  "mfa_setup_started",
  "mfa_enabled",
  "mfa_verify_success",
  "mfa_verify_failure",
  "mfa_recovery_code_used",
  "mfa_reset_by_admin",
  "mfa_disabled",
  "mfa_policy_changed",
  "mfa_required_set",
]);

export const auditLogsTable = pgTable("audit_logs", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").references(
    () => organizationsTable.id,
    { onDelete: "set null" }
  ),
  userId: text("user_id").references(() => usersTable.id),
  userName: text("user_name"),
  action: auditActionEnum("action").notNull(),
  entityType: text("entity_type").notNull(),
  entityId: text("entity_id").notNull(),
  entityLabel: text("entity_label"),
  previousValue: json("previous_value"),
  newValue: json("new_value"),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  timestamp: timestamp("timestamp").notNull().defaultNow(),
});

export type AuditLog = typeof auditLogsTable.$inferSelect;
